Feature/testimonials
GirlCodeZA/girlcode-website-project pull request #10
Opened 2022-03-30 12:59 UTC by Poison159

Added testimonials section to the Home Page

<img width="1429" alt="Screenshot 2022-03-30 at 14 57 22" src="https://user-images.githubusercontent.com/25311105/160839669-cdea1320-d206-41cd-8dfc-7ce39e4bf7d6.png">

2022-03-30 13:39 UTC, Zandile commented
@Poison159 happy with this. I will ask @mukwevhom to merge

2022-03-31 11:03 UTC, mukwevhom requested changes
@Poison159 Please check some of the suggestions I have added here

2022-03-31 11:03 UTC, mukwevhom commented on src/components/Testimonials.js
> +const Testimaonials = () => {
Please check the spelling here

2022-03-31 11:03 UTC, mukwevhom commented on src/components/Testimonials.js
> +        <div style={{textAlign:"center"}} className="row">
I'd suggest that you either use a bootstrap class or move it to the styles file

2022-03-31 11:03 UTC, mukwevhom commented on src/components/Testimonials.js
> +            <h4>OUR GIRL CODERS</h4>
Rather we use styles to make this uppercase

2022-04-05 08:46 UTC, Poison159 commented on src/components/Testimonials.js
> +            <h4>OUR GIRL CODERS</h4>
Hey there
I have made the requested changes and committed them to this branch -> [https://github.com/GirlCodeZA/girlcode-website-project/pull/10/commits/bed3550b3b56a704405392ffe21154b838aaa864](url)

Please let me know if there is anything else you would like me to do.

2022-04-07 07:04 UTC, Poison159 commented on src/components/Testimonials.js
> +            <h4>OUR GIRL CODERS</h4>
Hey @mukwevhom i have moved the css to a css file. 

Please let me know if you need anything else

2022-04-07 07:05 UTC, Poison159 commented on src/components/Testimonials.js
> +            <h4>OUR GIRL CODERS</h4>
oh here is where it is -> https://github.com/GirlCodeZA/girlcode-website-project/pull/10/commits/d572f556fecb27a5db1635957ea848db01627800

2022-04-07 08:10 UTC, mukwevhom approved these changes
Looks good to me

2022-04-07 08:24 UTC, merged